/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package login;

import java.awt.Color;

/**
 *
 * @author USER
 */
public class LOGIN extends javax.swing.JFrame {

    int xMouse,yMouse;
    public LOGIN() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bg = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        loGO = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        userLabel = new javax.swing.JLabel();
        usertxt = new javax.swing.JTextField();
        jSeparator4 = new javax.swing.JSeparator();
        contraseñaLabel = new javax.swing.JLabel();
        contraseñatxt = new javax.swing.JPasswordField();
        jSeparator1 = new javax.swing.JSeparator();
        LoginBTN = new javax.swing.JPanel();
        loginbtntxt = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        exitBtn = new javax.swing.JPanel();
        exittxt = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocationByPlatform(true);
        setUndecorated(true);
        setResizable(false);

        bg.setBackground(new java.awt.Color(255, 255, 255));
        bg.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Yu Gothic", 0, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("UES FMO");
        bg.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 290, -1, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/tienda (2).png"))); // NOI18N
        bg.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, -30, 370, 540));

        loGO.setFont(new java.awt.Font("Yu Gothic UI Light", 0, 24)); // NOI18N
        loGO.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/favicon.png"))); // NOI18N
        loGO.setText("FMOcc");
        bg.add(loGO, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 80, -1, -1));

        jLabel3.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 24)); // NOI18N
        jLabel3.setText("INICIAR SESION");
        bg.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 150, -1, -1));

        userLabel.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 18)); // NOI18N
        userLabel.setText("USUARIO");
        bg.add(userLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 210, -1, -1));

        usertxt.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        usertxt.setForeground(new java.awt.Color(204, 204, 204));
        usertxt.setText("ingrese su nombre de usuario");
        usertxt.setBorder(null);
        usertxt.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                usertxtMousePressed(evt);
            }
        });
        bg.add(usertxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 250, 300, -1));
        bg.add(jSeparator4, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 270, 300, -1));

        contraseñaLabel.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 18)); // NOI18N
        contraseñaLabel.setText("CONTRASEÑA");
        bg.add(contraseñaLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 290, -1, -1));

        contraseñatxt.setForeground(new java.awt.Color(204, 204, 204));
        contraseñatxt.setText("********");
        contraseñatxt.setBorder(null);
        contraseñatxt.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                contraseñatxtMousePressed(evt);
            }
        });
        bg.add(contraseñatxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 320, 300, -1));
        bg.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 340, 300, -1));

        LoginBTN.setBackground(new java.awt.Color(0, 134, 190));

        loginbtntxt.setEditable(false);
        loginbtntxt.setBackground(new java.awt.Color(0, 134, 190));
        loginbtntxt.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 14)); // NOI18N
        loginbtntxt.setForeground(new java.awt.Color(255, 255, 255));
        loginbtntxt.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        loginbtntxt.setText("ENTRAR");
        loginbtntxt.setBorder(null);
        loginbtntxt.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        loginbtntxt.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                loginbtntxtMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                loginbtntxtMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                loginbtntxtMouseExited(evt);
            }
        });

        javax.swing.GroupLayout LoginBTNLayout = new javax.swing.GroupLayout(LoginBTN);
        LoginBTN.setLayout(LoginBTNLayout);
        LoginBTNLayout.setHorizontalGroup(
            LoginBTNLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(loginbtntxt, javax.swing.GroupLayout.DEFAULT_SIZE, 130, Short.MAX_VALUE)
        );
        LoginBTNLayout.setVerticalGroup(
            LoginBTNLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(loginbtntxt, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
        );

        bg.add(LoginBTN, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 380, 130, 50));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                jPanel1MouseDragged(evt);
            }
        });
        jPanel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jPanel1MousePressed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 780, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 60, Short.MAX_VALUE)
        );

        bg.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 0, 780, 60));

        exitBtn.setBackground(new java.awt.Color(255, 255, 255));

        exittxt.setText("     X");
        exittxt.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        exittxt.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                exittxtMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                exittxtMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                exittxtMouseExited(evt);
            }
        });

        javax.swing.GroupLayout exitBtnLayout = new javax.swing.GroupLayout(exitBtn);
        exitBtn.setLayout(exitBtnLayout);
        exitBtnLayout.setHorizontalGroup(
            exitBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(exitBtnLayout.createSequentialGroup()
                .addComponent(exittxt, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 39, Short.MAX_VALUE))
        );
        exitBtnLayout.setVerticalGroup(
            exitBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(exitBtnLayout.createSequentialGroup()
                .addComponent(exittxt, javax.swing.GroupLayout.DEFAULT_SIZE, 49, Short.MAX_VALUE)
                .addContainerGap())
        );

        bg.add(exitBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 70, 60));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bg, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bg, javax.swing.GroupLayout.PREFERRED_SIZE, 501, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jPanel1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel1MousePressed
        xMouse =evt.getX();
        yMouse=evt.getY();
    }//GEN-LAST:event_jPanel1MousePressed

    private void jPanel1MouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel1MouseDragged
        int x =evt.getXOnScreen();
        int y = evt.getYOnScreen();
        this.setLocation(x-xMouse, y-yMouse);
    }//GEN-LAST:event_jPanel1MouseDragged

    private void exittxtMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exittxtMouseClicked
        System.exit(0);
    }//GEN-LAST:event_exittxtMouseClicked

    private void exittxtMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exittxtMouseEntered

        exitBtn.setBackground(Color.red);
        exittxt.setForeground(Color.white);
    }//GEN-LAST:event_exittxtMouseEntered

    private void exittxtMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exittxtMouseExited
        exitBtn.setBackground(Color.white);
        exittxt.setForeground(Color.black);
    }//GEN-LAST:event_exittxtMouseExited

    private void loginbtntxtMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_loginbtntxtMouseEntered
        loginbtntxt.setBackground(new Color(0,156,223));
    }//GEN-LAST:event_loginbtntxtMouseEntered

    private void loginbtntxtMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_loginbtntxtMouseExited
        loginbtntxt.setBackground(new Color(0,134,190));
    }//GEN-LAST:event_loginbtntxtMouseExited

    private void usertxtMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_usertxtMousePressed
       if(usertxt.getText().equals("ingrese su nombre de usuario"))
        usertxt.setText("");
      usertxt.setForeground(Color.black);
      if(String.valueOf(contraseñatxt.getPassword()).isEmpty()){
           
       }
        contraseñatxt.setText("********");
        contraseñatxt.setForeground(Color.gray);
    }//GEN-LAST:event_usertxtMousePressed

    private void contraseñatxtMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_contraseñatxtMousePressed
         if(String.valueOf(contraseñatxt.getPassword()).equals("********")){
        contraseñatxt.setText("");
        contraseñatxt.setForeground(Color.black);
        }
        if (usertxt.getText().isEmpty()){
        usertxt.setText("ingrese su nombre de usuario");
        usertxt.setForeground(Color.gray);
        }
    }//GEN-LAST:event_contraseñatxtMousePressed

    private void loginbtntxtMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_loginbtntxtMouseClicked
       javax.swing.JOptionPane.showMessageDialog(this,"intento de login con los datos:\nUsuario:"+usertxt.getText()+"\ncontraseña:"+String.valueOf(contraseñatxt.getPassword()),"LOGIN",javax.swing.JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_loginbtntxtMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LOGIN.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LOGIN.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LOGIN.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LOGIN.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LOGIN().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel LoginBTN;
    private javax.swing.JPanel bg;
    private javax.swing.JLabel contraseñaLabel;
    private javax.swing.JPasswordField contraseñatxt;
    private javax.swing.JPanel exitBtn;
    private javax.swing.JLabel exittxt;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JLabel loGO;
    private javax.swing.JTextField loginbtntxt;
    private javax.swing.JLabel userLabel;
    private javax.swing.JTextField usertxt;
    // End of variables declaration//GEN-END:variables
}
